cc_library(
    name = "ch",
    srcs = [
        "ChReqBatch.cpp",
        "ChWriter.cpp"
    ],
    hdrs = [
        "ChReqBatch.h",
        "ChWriter.h"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//httpcli"
    ],
    copts = ["-Isrc"]
)