
cc_test(
    name = "001_move",
    srcs = ["ut_move.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//junk/cpp/common"
    ],
    visibility = ["//visibility:public"]
)
