
cc_test(
    name = "003_concurrency",
    srcs = ["ut_concurrency.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//junk/cpp/common"
    ],
    visibility = ["//visibility:public"]
)
