
cc_test(
    name = "004_ch_writer",
    srcs = ["ut_ch_writer.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//ch/ut"
    ],
    visibility = ["//visibility:public"]
)
