test_suite(
    name = "tests",
    tests = [
    "//src/misc/tests/001_chrono",
    "//src/misc/tests/002_misc",
    "//src/misc/tests/003_merge_queue",
    "//src/misc/tests/004_ch_writer",
    "//src/misc/tests/005_kafka_sim"
    ]
)