
cc_test(
    name = "013_merge_queue",
    srcs = ["ut_merge_queue.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/misc/ut"
    ],
    visibility = ["//visibility:public"]
)
