
cc_test(
    name = "001_chrono",
    srcs = ["ut_chrono.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/misc"
    ],
    visibility = ["//visibility:public"]
)
