
cc_test(
    name = "005_kafka_sim",
    srcs = ["ut_kafka_sim.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
 #       "@ada//:ada",
        "//kafkawrap/ut"
    ],
    visibility = ["//visibility:public"]
)
