
cc_test(
    name = "012_misc",
    srcs = ["ut_misc.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//src/misc/ut"
    ],
    visibility = ["//visibility:public"]
)
