
cc_test(
    name = "003_class_design",
    srcs = ["ut_class_design.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//junk/cpp/common"
    ],
    visibility = ["//visibility:public"]
)
