cc_binary(
    name = "simd_hello",
    srcs = [
        "simd_utils.h",
        "simd_hello.cpp"
    ],
    deps = [
    ],
    copts = [
    ],
    linkopts = [],
    visibility = ["//visibility:public"]
)