
cc_test(
    name = "000_remove_spaces",
    srcs = ["ut_remove_spaces.cpp"],
    copts = ["-Isrc/"],
    deps = [
        "@catch2//:catch2_main",
        "//junk/cpp/common"
    ],
    visibility = ["//visibility:public"]
)
